- name: create iscsi-provisioner directory
  file:
    path: $HOME/iscsi-provisioner
    state: directory

- name: copy iscsi-secret.yml
  vars:
    USERNAME: "{{ ISCSI_TARGETD_USERNAME | b64encode }}"
    PASSWORD: "{{ ISCSI_TARGETD_PASSWORD | b64encode }}"
  template:
    src: iscsi-secret.yml.j2
    dest: $HOME/iscsi-provisioner/iscsi-secret.yml

- name: copy session-chap-credential.properties
  vars:
    USERNAME: "{{ ISCSI_TARGETD_USERNAME | b64encode }}"
    PASSWORD: "{{ ISCSI_TARGETD_PASSWORD | b64encode }}"
  template:
    src: session-chap-credential.properties.j2
    dest: $HOME/iscsi-provisioner/session-chap-credential.properties

- name: copy iscsi-chap-secret.yml
  vars:
    USERNAME: "{{ ISCSI_TARGETD_USERNAME | b64encode }}"
    PASSWORD: "{{ ISCSI_TARGETD_PASSWORD | b64encode }}"
  template:
    src: iscsi-chap-secret.yml.j2
    dest: $HOME/iscsi-provisioner/iscsi-chap-secret.yml

- name: download iscsi-provisioner
  get_url:
    url: https://raw.githubusercontent.com/kubernetes-incubator/external-storage/master/iscsi/targetd/kubernetes/iscsi-provisioner-d.yaml
    dest: $HOME/iscsi-provisioner/

- name: change iscsi server address in iscsi-provisioner file
  replace:
    path: $HOME/iscsi-provisioner/iscsi-provisioner-d.yaml
    regexp: '192.168.99.100'
    replace: "{{ ISCSI_SERVER_ADDRESS }}"

- name: create iscsi-provisioner (1/3)
  shell: kubectl apply -f iscsi-chap-secret.yml >> iscsi-provisioner-chap-secret.txt
  args:
    chdir: $HOME/iscsi-provisioner
    creates: iscsi-provisioner-chap-secret.txt

- name: create iscsi-provisioner (2/3)
  shell: kubectl apply -f iscsi-secret.yml >> iscsi-provisioner-secret.txt
  args:
    chdir: $HOME/iscsi-provisioner
    creates: iscsi-provisioner-secret.txt

- name: create iscsi-provisioner (3/3)
  shell: kubectl apply -f iscsi-provisioner-d.yaml >> iscsi-provisioner-d.txt
  args:
    chdir: $HOME/iscsi-provisioner
    creates: iscsi-provisioner-d.txt
