- name: install iscsi-initiator-utils
  yum:
    name: iscsi-initiator-utils
    state: present

- name: configure initiator name
  lineinfile:
    path: /etc/iscsi/initiatorname.iscsi
    regexp: 'InitiatorName'
    line: 'InitiatorName=iqn.1994-05.local.kubernetes:{{ inventory_hostname }}'
  register: iscsi_initiatorname

- name: enable and start iscsid service
  systemd:
    name: iscsid
    enabled: yes
    state: started

- name: restart iscsid service
  systemd:
    name: iscsid
    state: restarted
  when: iscsi_initiatorname.changed

